// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL6KUgx-Jmlw7gdIj8eKBfus-tIdPR9jk',
    appId: '1:336304343368:web:f1c425ebc2edd5e7b14b7d',
    messagingSenderId: '336304343368',
    projectId: 'pawfectcare-8d21c',
    authDomain: 'pawfectcare-8d21c.firebaseapp.com',
    storageBucket: 'pawfectcare-8d21c.firebasestorage.app',
    measurementId: 'G-6Z9EC46J45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRYiWtiWsvPs-G2t5NfdmYocofGii0UfA',
    appId: '1:336304343368:android:faa6edb146ef0ed3b14b7d',
    messagingSenderId: '336304343368',
    projectId: 'pawfectcare-8d21c',
    storageBucket: 'pawfectcare-8d21c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhHD8llLcz3BNAAyrXoJnebrhrHytuHxE',
    appId: '1:336304343368:ios:f67df68ac3705e96b14b7d',
    messagingSenderId: '336304343368',
    projectId: 'pawfectcare-8d21c',
    storageBucket: 'pawfectcare-8d21c.firebasestorage.app',
    iosBundleId: 'com.mycompany.pawfectcare',
  );
}
